language: c
before_install:
  - pip install --user cpp-coveralls
before_script:
  - cmake -DCMAKE_BUILD_TYPE=Testing
script:
  - make && make test
after_success:
  - coveralls --exclude CMakeFiles --exclude test --exclude lib --gcov-options '\-lp'
