language: c
before_install:
  - pip install --user cpp-coveralls
before_script:
 - mkdir build
 - cd build 
 - cmake -DCMAKE_BUILD_TYPE=Testing ..
script:
  - make && make test
after_success:
  - coveralls --exclude test --exclude lib --gcov-options '\-lp'
